services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api/afisha"
        VITE_CDN_URL: "/content/afisha"
    image: ghcr.io/z-u-s-h-o/film-react-nest/frontend:latest
    container_name: frontend
    networks:
      - webnet
    volumes:
      - frontend_dist:/usr/share/nginx/html
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/z-u-s-h-o/film-react-nest/backend:latest
    container_name: backend
    networks:
      - webnet
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/film_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - NODE_ENV=development
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    networks:
      - webnet
    environment:
      - POSTGRES_DB=film_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - webnet
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/z-u-s-h-o/film-react-nest/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist:

networks:
  webnet:
    driver: bridge
